Create a base of context menu
bistro-tech/bartender pull request #2
Opened 2024-07-21 21:14 UTC by Arthur-Devs

2024-07-29 09:22 UTC, Arthur-Devs commented on src/bot.ts
> +        await this.registerSlashCommands(guilds);
return instead of await

2024-07-29 09:22 UTC, Arthur-Devs commented on src/log/loggable/context.ts
> +                    value: `\`${this.interaction.applicationId}\``,
Change this

2024-07-29 09:26 UTC, vic1707 requested changes

2024-07-29 09:26 UTC, vic1707 commented on src/contextMenus/report.ts
> +): Promise<Message<true>> {
si <true> c'est quand tout va bien alors tu ne peux pas le mettre ici vu que la promesse n'est pas resolue actuellement, non ?

2024-08-11 22:36 UTC, Arthur-Devs commented on src/contextMenus/report.ts
> +): Promise<Message<true>> {
Je suis pas sûr de comprendre c'était par rapport au <true> ?

2024-08-12 09:19 UTC, vic1707 approved these changes

2024-08-12 09:27 UTC, merged